import "./globals.css"
export default function Home() {
  return (

    <div>
      <p className="m-2 max-w-4xl mx-auto font-mono rounded-xl backdrop-blur-2xl text-black p-2">
        <b>
          What are DAOs and how do they work?
        </b>
        <br />

        DAOs are blockchain-based communities that are designed to bring a new, more open and
        democratic management structure to businesses and other collaborative projects in web3. DAOs are
        owned by their members, who collectively make decisions and manage their funds through smart
        contracts and tokens. DAOs operate without centralized leadership, and the rules and processes of
        their governance are often determined by the code governing the project.
        <br />
        <br />
        Historical evolution of DAOs. DAOs are inspired by the concept of decentralization and autonomy that
        underlies the blockchain technology and the cryptocurrency movement. Some would argue that
        Bitcoin was the first DAO, as it is a peer-to-peer network that is governed by a set of rules and
        incentives that are enforced by the code and the consensus mechanism.
        <br />
        <br />
        However, DAOs as we know
        them today emerged with the advent of smart contracts, which are self-executing agreements that
        run on the blockchain. The first attempt to create a DAO was The DAO, a project that raised over $150
        million in 2016 to fund various web3 ventures. However, The DAO was hacked and lost about a third
        of its funds, leading to a controversial hard fork of Ethereum and the creation of Ethereum Classic.
        Since then, DAOs have evolved and diversified, and have been used for various purposes and
        functions, such as DeFi, NFT, social impact, media, and more.
      </p>

      <p className="paragraph m-2 max-w-4xl mx-auto font-mono rounded-xl backdrop-blur-2xl text-black p-2">
        <b>
          Key components of a DAO. A DAO typically consists of the following components:
        </b>
        <br />
        <ol>
          <li>
            A smart contract platform, such as Ethereum, that provides the infrastructure and the tools for
            creating and running DAOs.
          </li>

          <li>
            A governance token, which is a type of crypto asset that may entitle the holder to DAO membership
            and voting rights.
          </li>

          <li>
            Governance tokens are usually distributed to the project’s founders, users, backers, and other stakeholders, and can be traded on secondary markets.
          </li>

          <li>
            A treasury, which is a pool of funds that is controlled by the DAO and used to finance the project’s
            activities and initiatives.
          </li>

          <li>
            The treasury is usually funded by the token sales, fees, donations, or
            revenues generated by the DAO.
          </li>

          <li>
            A proposal system, which is a mechanism for submitting, reviewing, and voting on project ideas, requests, or changes.
          </li>

          <li>
            Proposals are usually created by the DAO members and require a certain
            quorum and majority to be approved and executed.
          </li>

          <li>
            A community, which is a group of people who share the same vision and values and participate in theDAO’s governance and operations. The community usually communicates and coordinate
          </li>

        </ol>
      </p>
    </div>
  )
}
